Add support for digital credentials API
a-sit-plus/valera pull request #151
Opened 2024-12-20 13:15 UTC by gp-iaik

Known issues:

- Race condition between home view and authentication view on startup (workaround by adding delay)
- Cannot access translations for attribute names outside compose method (attribute names are not translated into a friendly name when registering the credentials with the system, app name hardcoded)

2025-01-07 04:36 UTC, JesusMcCloud commented
Can you elaborate on why no proper fix for the race condition was implemented?

2025-01-07 15:51 UTC, nodh commented
Enable flag in Google Chrome on Android under `chrome://flags`, and head to <https://digital-credentials.dev/> to request (but not age over 21), and choose "Request Credentials (Preview)"

2025-01-07 15:56 UTC, nodh requested changes

2025-01-07 15:56 UTC, nodh commented on shared/src/androidInstrumentedTest/kotlin/AndroidDummyPlatformAdapter.kt
> +    override fun sendAPIResultBack(responseJson: ByteArray, dcApiRequest: DCAPIRequest) {
Please provide a better name for the method (also in the interface)

2025-01-07 16:08 UTC, md4096 commented
Please try this commit b85571e01ad9e61af2506515120727c124946b51 if it fixes the race condition

2025-01-07 16:13 UTC, gp-iaik commented on androidApp/src/androidMain/kotlin/at/asitplus/wallet/app/android/MainActivity.kt
> +        appLink.value = if (intent.action == "androidx.identitycredentials.action.GET_CREDENTIALS") intent.action else intent.data?.toString()
Tatsächlich, und die funktioniert sogar im Vergleich zu den anderen.

2025-01-07 16:20 UTC, nodh commented on shared/src/androidMain/kotlin/main.android.kt
> +            } else {
So this doesn't help? https://github.com/openwallet-foundation-labs/identity-credential/blob/d7a37a5c672ed6fe1d863cbaeb1a998314d19fc5/wallet/src/main/java/com/android/identity_credential/wallet/credman/CredmanPresentationActivity.kt#L299

2025-01-07 16:22 UTC, JesusMcCloud commented on shared/build.gradle.kts
> +                implementation("org.bouncycastle:bcpkix-jdk18on:1.78.1")
in general: use libs.versions.toml and check against https://github.com/a-sit-plus/gradle-conventions-plugin as it already provides helpers for BC and others

2025-01-07 16:24 UTC, gp-iaik commented on shared/src/androidMain/kotlin/dcapi/WalletAPIData.kt
> +data class WalletAPIData(var intent: Intent? = null)
Since there are three different namespaces in that module, which one of the other two should I choose: at.asitplus.wallet.app.android.dcapi or at.asitplus.wallet.app.valera.dcapi? Or even at.asitplus.wallet.app.valera.android.dcapi?

2025-01-07 16:25 UTC, gp-iaik commented on shared/src/commonMain/kotlin/App.kt
> +        // TODO is this the best place to sync the credentials with the system?
Is there a definitive place where I could add it? What about revocation and other edge cases?

2025-01-07 16:31 UTC, gp-iaik commented on shared/build.gradle.kts
> +                implementation("com.android.identity:identity-android:202411.1")
Yes. (It's KMP though, if that's why you're asking)

2025-01-07 17:10 UTC, gp-iaik commented on shared/src/androidMain/kotlin/main.android.kt
> +            } else {
Not as long as I don't have an openid4vp wasm matcher that I can register with the system.

2025-01-07 17:14 UTC, gp-iaik commented on shared/src/androidInstrumentedTest/kotlin/AndroidDummyPlatformAdapter.kt
> +    override fun sendAPIResultBack(responseJson: ByteArray, dcApiRequest: DCAPIRequest) {
Changed with https://github.com/a-sit-plus/valera/commit/d0e85186abd131da21e75e8f9b093ecab10777a6

2025-01-07 17:15 UTC, gp-iaik commented on shared/build.gradle.kts
> +                implementation("org.bouncycastle:bcpkix-jdk18on:1.78.1")
Removed dependency, seems that Security.addProvider was the only thing that was needed to get the Google library working.

2025-01-07 17:18 UTC, gp-iaik commented on androidApp/src/androidMain/kotlin/at/asitplus/wallet/app/android/MainActivity.kt
> +    private fun finishAPIRequest(resultJson: String) {
Changed with https://github.com/a-sit-plus/valera/commit/d0e85186abd131da21e75e8f9b093ecab10777a6

2025-01-07 17:18 UTC, gp-iaik commented on androidApp/src/androidMain/kotlin/at/asitplus/wallet/app/android/MainActivity.kt
> +        appLink.value = if (intent.action == "androidx.identitycredentials.action.GET_CREDENTIALS") intent.action else intent.data?.toString()
Changed with https://github.com/a-sit-plus/valera/commit/d0e85186abd131da21e75e8f9b093ecab10777a6

2025-01-07 18:39 UTC, nodh commented on shared/src/androidMain/kotlin/dcapi/WalletAPIData.kt
> +data class WalletAPIData(var intent: Intent? = null)
I would go with `at.asitplus.wallet.app.android`, since it's in `androidMain`, just like the `MainActivity`.

2025-01-07 20:22 UTC, gp-iaik commented on shared/src/androidMain/kotlin/dcapi/WalletAPIData.kt
> +data class WalletAPIData(var intent: Intent? = null)
Changed in https://github.com/a-sit-plus/valera/pull/151/commits/5b8308c704fa9cb5f4cfc83b8e8069ff9bc44e36

2025-01-07 20:23 UTC, gp-iaik commented on shared/src/commonMain/kotlin/domain/BuildAuthenticationConsentPageFromAuthenticationRequestDCAPIUseCase.kt
> +package domain
Changed in https://github.com/a-sit-plus/valera/pull/151/commits/5b8308c704fa9cb5f4cfc83b8e8069ff9bc44e36

2025-01-07 20:35 UTC, gp-iaik commented on shared/src/commonMain/kotlin/data/dcapi/CredentialField.kt
> +package data.dcapi
Added comment in https://github.com/a-sit-plus/valera/commit/7e9cfba3d7c687ec692932f994dc8c68f5433691

2025-01-08 10:32 UTC, nodh commented on shared/src/commonMain/kotlin/App.kt
> +        // TODO is this the best place to sync the credentials with the system?
Revocation isn't implemented yet ... so maybe just leave it here, and find a better place later on

2025-01-08 11:24 UTC, gp-iaik commented
> Please try this commit [b85571e](https://github.com/a-sit-plus/valera/commit/b85571e01ad9e61af2506515120727c124946b51) if it fixes the race condition

Looks like it fixes the problem 👍

2025-01-08 11:27 UTC, nodh approved these changes

2025-01-08 12:05 UTC, merged

2025-01-08 16:34 UTC, JesusMcCloud commented
Missing iOS implementation!