Feature/logo
a-sit-plus/valera pull request #152
Opened 2024-12-21 12:28 UTC by JesusMcCloud

* Adds the "A-SIT Plus GmbH" Logo to the headers of all screens.
* More consistent Font site of header
  * to make logo fit on all screens without text wrapping
  * and to make sense: All Non-Toplevel Nav headers now use the same, slightly smaller font size
* Removed the "Delete" Action from the credentials details screen:
  * Because it messes up the Logo placement and we can't to anything about it
  * Because this exact same functionality is available on the credentials overview

EDIT: Removed old Screenshots

2025-01-07 17:12 UTC, gp-iaik commented
Wouldn't it look better with a margin?

2025-01-07 18:01 UTC, JesusMcCloud commented
you mean on the bottom?

2025-01-07 18:36 UTC, nodh requested changes
I would make the logo way smaller, then there's also a margin around it

2025-01-07 18:36 UTC, nodh commented on shared/src/commonMain/kotlin/ui/views/CredentialDetailsView.kt
> +                /*actions = {
Why is this code commented-out?

2025-01-07 18:59 UTC, JesusMcCloud commented on shared/src/commonMain/kotlin/ui/views/CredentialDetailsView.kt
> +                /*actions = {
removes the delete button from the details view, because it does not work with the logo at all. There's simply no way to have the logo and the three-dots menu here is a satisfying way.

2025-01-07 19:07 UTC, nodh commented on shared/src/commonMain/kotlin/ui/views/CredentialDetailsView.kt
> +                /*actions = {
So then w'ell need to add a button to the details view and remove the code here?

2025-01-07 19:31 UTC, JesusMcCloud commented on shared/src/commonMain/kotlin/ui/views/CredentialDetailsView.kt
> +                /*actions = {
the button is already in the credentials list, so you can still remove it. where this button would fit in this view then, I don't know.

2025-01-07 20:08 UTC, JesusMcCloud commented
Updated Logo size:

![image](https://github.com/user-attachments/assets/8ab12e5e-057c-420e-a1e1-67e8ad9a23bd)

2025-01-08 09:50 UTC, JesusMcCloud commented
Actually, with the small logo, it is not too bad:

![image](https://github.com/user-attachments/assets/cd61610b-1604-49fa-9b54-8c294947bfee)

2025-01-08 09:54 UTC, JesusMcCloud commented
How about this? @nodh @FelixHoer 

![image](https://github.com/user-attachments/assets/b10580ff-d8c0-4001-9b2c-8e8de31a2ecf)

2025-01-08 09:57 UTC, JesusMcCloud commented
More Screenies with new logo:

![image](https://github.com/user-attachments/assets/9d0b35bb-500d-41cb-b756-a3ca9e3261e6)

![image](https://github.com/user-attachments/assets/324126e5-f3e7-4e3c-8b8a-52cec13c0dba)

![image](https://github.com/user-attachments/assets/2aa2a854-f2ee-471a-88ef-55209e7426a0)

![image](https://github.com/user-attachments/assets/97421d07-77f9-44f2-ae1b-b247d6c3443f)

![image](https://github.com/user-attachments/assets/f9e3ce05-17e5-4d9d-a003-d7ba18a9e588)

![image](https://github.com/user-attachments/assets/ec5c6cc8-f979-4f6e-919d-81b5db275f10)

2025-01-08 10:08 UTC, JesusMcCloud commented on shared/src/commonMain/kotlin/ui/views/CredentialDetailsView.kt
> +                /*actions = {
brought the menu back (see screenshots below)

2025-01-08 10:09 UTC, nodh approved these changes

2025-01-08 10:46 UTC, merged